name: rutino_customer
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.10.4


dependencies:
  flutter:
    sdk: flutter

  dio: ^5.4.0
  retrofit: ^4.1.0
  json_annotation: ^4.8.1
  provider: ^6.1.1 # Untuk state management tema
    
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.3.0
  http: ^0.13.6
  shared_preferences: ^2.5.4
  firebase_messaging: ^15.0.0
  firebase_core: ^3.15.2
  flutter_dotenv: ^5.2.0
  pinput: ^5.0.0
  intl: ^0.19.0
  flutter_secure_storage: ^10.0.0
  flutter_contacts: ^1.1.9+2
  permission_handler: ^11.3.1
  share_plus: ^7.2.0
  path_provider: ^2.1.0
  flutter_local_notifications: ^17.0.0

dev_dependencies:
  flutter_test:
  
    sdk: flutter

  retrofit_generator: ^8.1.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1


  flutter_lints: ^6.0.0
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_background: "#1DB954" # Ganti dengan kode warna Rutino
  remove_alpha_ios: true


flutter_native_splash:
  # Native splash screen untuk startup instan
  color: "#FFFFFF"
  image: assets/images/logo.png
  android: true
  ios: true
  web: false
  android_12:
    image: assets/images/logo.png
    color: "#FFFFFF"
  branding: assets/images/logo.png
  branding_dark: assets/images/logo.png


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/
    - .env

  